/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      // Ported verbatim from the Stitch design (design/design_reference.html).
      colors: {
        error: "#ba1a1a",
        "inverse-surface": "#31302e",
        "primary-fixed": "#e4e2e1",
        "on-primary-fixed": "#1b1c1c",
        "on-tertiary-fixed": "#1c1c18",
        "on-error-container": "#93000a",
        "secondary-fixed": "#ffe088",
        "error-container": "#ffdad6",
        outline: "#747878",
        "surface-container-low": "#f6f3ef",
        "tertiary-container": "#2e2d29",
        "on-secondary-container": "#745c00",
        "surface-bright": "#fcf9f5",
        "surface-container-high": "#eae8e4",
        "surface-tint": "#5f5e5e",
        "on-surface-variant": "#444748",
        "on-secondary-fixed": "#241a00",
        "primary-fixed-dim": "#c8c6c6",
        "on-primary-container": "#959494",
        "surface-variant": "#e5e2de",
        "secondary-container": "#fed65b",
        "secondary-fixed-dim": "#e9c349",
        secondary: "#735c00",
        "surface-dim": "#dcdad6",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#484742",
        "outline-variant": "#c4c7c7",
        "surface-container": "#f0ede9",
        "on-secondary-fixed-variant": "#574500",
        surface: "#fcf9f5",
        primary: "#181919",
        "on-surface": "#1c1c1a",
        "on-background": "#1c1c1a",
        "on-primary-fixed-variant": "#474747",
        "primary-container": "#2d2d2d",
        "surface-container-highest": "#e5e2de",
        "surface-container-lowest": "#ffffff",
        tertiary: "#191915",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#e6e2db",
        "inverse-primary": "#c8c6c6",
        "tertiary-fixed-dim": "#c9c6c0",
        "inverse-on-surface": "#f3f0ec",
        background: "#fcf9f5",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#97948e",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-sm": "12px",
        "margin-desktop": "64px",
        gutter: "24px",
        "stack-md": "24px",
        "margin-mobile": "20px",
        "container-max": "1200px",
        "stack-lg": "48px",
        unit: "8px",
      },
      // `max-w-*` reads from theme.maxWidth (not spacing), so expose the
      // container width here as well to make `max-w-container-max` work.
      maxWidth: {
        "container-max": "1200px",
      },
      fontFamily: {
        "display-lg": ["var(--font-libre)", "Georgia", "serif"],
        "headline-lg": ["var(--font-libre)", "Georgia", "serif"],
        "headline-md": ["var(--font-libre)", "Georgia", "serif"],
        "headline-lg-mobile": ["var(--font-libre)", "Georgia", "serif"],
        "body-lg": ["var(--font-manrope)", "system-ui", "sans-serif"],
        "body-md": ["var(--font-manrope)", "system-ui", "sans-serif"],
        "label-md": ["var(--font-manrope)", "system-ui", "sans-serif"],
        "label-sm": ["var(--font-manrope)", "system-ui", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
      },
      boxShadow: {
        soft: "0 10px 30px -12px rgba(24, 25, 25, 0.18)",
      },
    },
  },
  plugins: [],
};
